version: '3.8'
services:
  stats-server:
    build: ./stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_HOST=stats_db
      - DB_NAME=statsDB
      - DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db
    ports:
      - "6541:5432"
    environment:
          - POSTGRES_DB=statsDB
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=root
          - PGHOST=stats_db

  ewm-service:
    build: ./main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - DB_HOST=ewm_db
      - DB_NAME=mainDB
      - DB_PORT=5432

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
          - POSTGRES_DB=mainDB
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=root
          - PGHOST=ewm_db
